
name: Demo
on:
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: "Are you feeling good?"
        type: boolean
        default: false
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "we are learning github actions"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: Step2
        run: echo "This is step2 with need of greeting"
      - name: step3
        if: ${{inputs.areYouFeelingGood}}
        run: echo "i am doing grat!
      - name: step4
        if: ${{inputs.areYouFeelingGood}}
        run: echo "i am not good"
