name: Demo

on:
  workflow_dispatch:
    inputs:
      areYouFeelingGood:
        description: "Are you felling good ?"
        type: boolean
        default: false
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "We are learning github actions"
  Job2:
    runs-on: ubuntu-latest
    needs: [Job1]
    steps:
      - name: Step2
        run: echo "This is step2 with need for greeting"
      - name: step3
        if: ${{inputs.areYouFeelingGood}}
        run: echo "I am doing great "
      - name: step4
        if: ${{}}

